version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_video_creator
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./app:/app/app  # Hot reload for development
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_video_creator
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - db
      - redis
    command: celery -A app.worker worker --loglevel=info

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ai_video_creator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Optional: Flower for monitoring Celery tasks
  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: celery -A app.worker flower

volumes:
  postgres_data:
  redis_data: